packages:
  - "packages/*"
  - "services/*"
  - "apps/*"
  - "UI"

allowBuilds:
  esbuild: true
  "@reown/appkit": true
  bufferutil: true
  keccak: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - fastify@5.12.3
